declare component DSwitch: input -> output

################
# SEQUENCES
################
sequence toehold 	= "?N" : 5

sequence input 		= "?N" : 15
sequence output		= "?N" : 15

sequence gatea 		= "?N" : 15
sequence siga		= "?N" : 15


################
# STRANDS
################
strand st_in_signal		= input toehold gatea toehold : 40
strand st_a_signal		= toehold siga : 20

strand st_gatea_switch	= siga toehold : 20
strand st_gatea_output	= gatea toehold output toehold : 40
strand st_gatea_base	= toehold* gatea* toehold* siga* toehold* : 45


################
# STRUCTURES
################
structure In_Signal			= st_in_signal : domain ....
structure A_Signal			= st_a_signal : domain ..

structure Gatea				= st_gatea_switch + st_gatea_output + st_gatea_base : domain ((+((..+)))).
structure Gatea_Interm 		= st_gatea_switch + st_gatea_output + st_gatea_base : domain ((+((..+)).))
structure Gatea_Output		= st_gatea_output : domain ....

structure Gatea_Waste1		= st_gatea_switch : domain ..
structure Gatea_Waste2 		= st_a_signal + st_in_signal + st_gatea_base : domain ((+.(((+)))))


################
# KINETICS
################
kinetic A_Signal + Gatea -> Gatea_Waste1 + Gatea_Interm
kinetic In_Signal + Gatea_Interm -> Gatea_Waste2 + Gatea_Output

