declare component PSwitch: input -> output


################
# SEQUENCES
################
sequence toehold 	= "?N" : 5

sequence input 		= "?N" : 15
sequence output		= "?N" : 15

sequence gatea 		= "?N" : 15


################
# STRANDS
################
strand st_in_signal		= input toehold gatea toehold : 40

strand st_gatea1_output = gatea toehold output toehold : 40
strand st_gatea1_base   = toehold* gatea* toehold* : 25

strand st_gatea2_output = gatea toehold : 20
strand st_gatea2_base	= toehold* gatea* toehold* : 25


################
# STRUCTURES
################
structure In_signal			= st_in_signal : domain ....
structure Gatea1_Output		= st_gatea1_output : domain ....
structure Gatea2_Output		= st_gatea2_output : domain ..

structure Gatea1			= st_gatea1_output + st_gatea1_base : domain ((..+)).
structure Gatea2		 	= st_gatea2_output + st_gatea2_base : domain ((+)).

structure Gatea1_Waste		= st_in_signal + st_gatea1_base : domain .(((+)))
structure Gatea2_Waste		= st_in_signal + st_gatea2_base : domain .(((+)))


################
# KINETICS
################
kinetic In_signal + Gatea1 -> Gatea1_Waste + Gatea1_Output
kinetic In_signal + Gatea2 -> Gatea2_Waste + Gatea2_Output
