declare component DAOEtile3up_hp: sLL + sLR -> sUL + sUR

## Sequences
# sticky ends
sequence sLL = "5N" : 5
sequence sUL = "5N" : 5
sequence sLR = "5N" : 5
sequence sUR = "5N" : 5

# core 
sequence sULarm = "S 7N" : 8
sequence sUcore = "S 14N S" : 16
sequence sURarm = "7N S" : 8 
sequence sLLarm = "S 7N" : 8 
sequence sLcoreL = "S 7N" : 8
sequence sLcoreR = "7N S" : 8
sequence sLRarm = "7N S" : 8
sequence sLhair = "8N" : 8
sequence sRhair = "8N" : 8

## Strands
strand longLeft   = sULarm sUcore sLcoreR* sLhair "TTTT" sLhair* "TT" sLcoreL* sLLarm* : 70
strand longRight  = sURarm* sUcore* sLcoreL sRhair "TTTT" sRhair* "TT" sLcoreR sLRarm : 70
strand shortLeft  = sLL sLLarm sULarm* sUL : 26
strand shortRight = sLR sLRarm* sURarm sUR : 26

## Structures
structure [no-opt] tile = shortLeft + longLeft + longRight + shortRight : 26. + 70. + 70. + 26.  
# This is a dummy structure that tells the designer that these strands are in a 
#   complex, but provides no further base-pairing information because we don't 
#   "yet" handle psuedoknots
