declare component gate_uni_react(t, bm, c): B -> Out

### Domains
# Toeholds:
sequence toe-fb = "<t>H"
sequence toe-sb = "<t>H"

# Branch migration domains:
sequence bm  = "<bm - c>H"
sequence ch = "C<bm - c - 1>H"

# Clamps:
sequence cbm  = "W<c-1>C"
sequence cch = "C<c-1>W"

### I/O connectors
sequence B = toe-sb bm cbm toe-fb
sequence Out = ch cch toe-sb bm cbm

### Strands
strand b = toe-sb bm cbm toe-fb
strand gate_base = toe-fb* cbm* bm* toe-sb* cch*
strand out = ch cch toe-sb bm cbm

### Structures
# Single-stranded:
structure B = b : domain ....
structure Out = out : domain .....

# Gates:
structure Gate = gate_base + out : domain .((((+.))))

# Waste products:
structure Gate_waste = gate_base + b : domain ((((.+))))

### Reactions
kinetic B + Gate -> Gate_waste
