declare component set_history_domains_equal(t, bm, c): A -> B

### Domains
# Toeholds:
sequence toe-fa = "<t>H"
sequence toe-sa = "<t>H"
sequence toe-fb = "<t>H"
sequence toe-sb = "<t>H"

# Branch migration domains:
sequence a  = "<bm - c>H"
sequence ah = "C<bm - c - 1>H"
sequence b  = "<bm - c>H"
# sequence bh = "C<bm - c - 1>H"

# Clamps:
sequence ca  = "W<c-1>C"
sequence cah = "C<c-1>W"
sequence cb  = "W<c-1>C"
# sequence cbh = "C<c-1>W"

### I/O connectors
# Signal Strands
sequence A = toe-sa a ca toe-fa ah cah
sequence B = toe-sb b cb toe-fb ah cah # This has only history domains equal

# Set all domains equal, except history domains
#equal ah bh
#equal cah cbh

# Declare as strands to avoid warnings
strand A_strand = toe-sa a ca toe-fa ah cah
strand B_strand = cah* ah* toe-fb* cb* b* toe-sb*

# Declare a structure where the identical components are complement-compatible
structure constraint = A_strand + B_strand : domain ....((+))....
