declare component set_signals_equal(l): AB -> CD

### Domains
# Subdomains:
# sequence ah1 = "<0>H"
# sequence ah2 = "<0>H"
sequence a1 = "<l>H"
sequence a2 = "<l>H"
sequence a3 = "<l>H"
sequence b1 = "<l>H"
sequence b2 = "<l>H"
sequence b3 = "<l>H"
sequence ch1 = "<l>H"
sequence ch2 = "<l>H"
sequence c1 = "<l>H"
sequence c2 = "<l>H"
sequence c3 = "<l>H"
sequence d1 = "<l>H"
sequence d2 = "<l>H"
sequence d3 = "<l>H"

### I/O connectors
sequence AB = b3 b2 b1 a3 a2 a1 #ah2 ah1
sequence CD = d3 d2 d1 c3 c2 c1 ch2 ch1

### Strands
strand ab = b3 b2 b1 a3 a2 a1 #ah2 ah1
strand cdComp = ch1* ch2* c1* c2* c3* d1* d2* d3*

### Structures
# Single-stranded:
structure AB = ab : domain ......
structure CDComp = cdComp : domain ........

# Gates:
structure Constraint = ab + cdComp : domain ((((((+..))))))
