declare component ReporterInverted(extra1, bm, toe, extra2): input -> 

## Sequences
sequence d1 = "?N" : <extra1>  # Corresponds to d13 in the 5'/3' inverted system
sequence d2 = "?N" : <bm>      # Corresponds to d1 + d2a in catalyst system
sequence d3 = "?N" : <toe>     # Corresponds to d2b in catalyst system
sequence d4 = "?N" : <extra2>  # Corresponds to d2c in catalyst system

## Sequences for system constraints
sequence input = d1 d2 d3 d4

## Strands
strand in  = d1 d2 d3 d4
strand out = d2
strand bot = d3* d2* 

## Structures/Complexes
# Input
structure Input = in : domain ....
# Gate (and Intermediate structures)
structure Reporter  = bot + out  : domain .(+)
# Outputs
structure Output = out : domain .
# Waste
structure Waste = bot + in : domain ((+.)).

## Kinetics
kinetic Reporter + Input -> Output + Waste


