declare component DAOEdoubletile35bh_down: sLL + sUL -> sUM + sUR
# bottom left tile is 3up, upper right tile is 5up
# bottom tile's bottom right sticky end is blunt; top tile's bottom right sticky end is hairpin
# just like Barish et al's Z56 for Variable-Width and Copy

## Sequences
# sticky ends
sequence sLL = "5N" : 5
sequence sUL = "5N" : 5
sequence sUM = "5N" : 5
sequence sUR = "5N" : 5

# core 
sequence sbULarm = "N 7N" : 8
sequence sbLLarm = "N 7N" : 8 
sequence sbLRarm = "N 12N" : 13
sequence sbUcore = "N 14N N" : 16
sequence sbLcore = "N 14N N" : 16
sequence sMarm   = "21N" : 21 
sequence stULarm = "N 7N" : 8
sequence stLRarm = "N 7N" : 8 
sequence stURarm = "N 7N" : 8
sequence stUcore = "N 14N N" : 16
sequence stLcore = "N 14N N" : 16
sequence stLRhairpin_arm = "7N" : 7


## Strands
strand shortLeft    = sLL sbLLarm sbULarm* sUL : 26
strand longLeft     = sbULarm sbUcore sbLcore* sbLLarm* : 48
strand longMidLeft  = sUM stULarm sMarm sbUcore* sbLcore sbLRarm* : 79
strand longMidRight = sbLRarm sMarm* stLcore stUcore* stULarm* : 74
strand longRight    = stLRarm stLcore* stUcore stURarm* : 48
strand shortRight   = sUR stURarm stLRarm* stLRhairpin_arm "TTTT" stLRhairpin_arm* : 39

## Structures
structure [no-opt] tile = shortLeft + longLeft + longMidLeft + longMidRight + longRight + shortRight : 26. + 48. + 79. + 74. + 48. + 39.  
# This is a dummy structure that tells the designer that these strands are in a 
#   complex, but provides no further base-pairing information because we don't 
#   "yet" handle psuedoknots
