declare component DAOEtile3up: sLL + sLR -> sUL + sUR

## Sequences
# sticky ends
sequence sLL = "5N" : 5
sequence sUL = "5N" : 5
sequence sLR = "5N" : 5
sequence sUR = "5N" : 5

# core 
sequence sULarm = "N 7N" : 8
sequence sUcore = "N 14N N" : 16
sequence sURarm = "7N N" : 8 
sequence sLLarm = "N 7N" : 8 
sequence sLcore = "N 14N N" : 16
sequence sLRarm = "7N N" : 8

## Strands
strand longLeft   = sULarm sUcore sLcore* sLLarm* : 48
strand longRight  = sURarm* sUcore* sLcore sLRarm : 48
strand shortLeft  = sLL sLLarm sULarm* sUL : 26
strand shortRight = sLR sLRarm* sURarm sUR : 26

## Structures
structure [no-opt] tile = shortLeft + longLeft + longRight + shortRight : 26. + 48. + 48. + 26.  
# This is a dummy structure that tells the designer that these strands are in a 
#   complex, but provides no further base-pairing information because we don't 
#   "yet" handle psuedoknots
